#pragma once

#define SETTINGS_APP_NAME "ApologyCounter"
#define SETTINGS_ORGANIZATION_NAME "WhenInDoubtC4"

#define DATA_ARRAY "counterData"
#define DATA_DISPLAY_NAME "displayName"
#define DATA_NAME "name"
#define DATA_COUNT "count"
#define DATA_TIME_DATA "timeData"
#define DATA_TIMESTAMP "timestamp"
#define DATA_SETTINGS "settings"
#define DATA_WIDGET "widget"
#define DATA_STYLE "style"

#define STYLE_TEXT 0xfafafa
#define STYLE_PRIMARY_LIGHT 0x4f5b62
#define STYLE_PRIMARY_DARK 0x000a12

#define STYLE_BLUE_SECONDARY 0x03a9f4
#define STYLE_BLUE_SECONDARY_LIGHT 0x67daff
#define STYLE_BLUE_SECONDARY_DARK 0x007ac1

#define STYLE_GREEN_SECONDARY 0x4caf50
#define STYLE_GREEN_SECONDARY_LIGHT 0x80e27e
#define STYLE_GREEN_SECONDARY_DARK 0x087f23

#define STYLE_PURPLE_SECONDARY 0x9c27b0
#define STYLE_PURPLE_SECONDARy_LIGHT 0xd05ce3
#define STYLE_PURPLE_SECONDARY_DARK 0x6a0080

#define STYLE_PINK_SECONDARY 0xe91e63
#define STYLE_PINK_SECONDARY_LIGHT 0xff6090
#define STYLE_PINK_SECONDARY_DARK 0xb0003a

#define STYLE_RED_SECONDARY 0xf44336
#define STYLE_RED_SECONDARY_LIGHT 0xff7961
#define STYLE_RED_SECONDARY_DARK 0xba000d

#define STYLE_YELLOW_SECONDARY 0xffeb3b
#define STYLE_YELLOW_SECONDARY_LIGHT 0xffff72
#define STYLE_YELLOW_SECONDARY_DARK 0xc8b900

#define STYLE_ORANGE_SECONDARY 0xff9800
#define STYLE_ORANGE_SECONDARY_LIGHT 0xffc947
#define STYLE_ORANGE_SECONDARY_DARK 0xc66900

#define STYLE_GREY_SECONDARY 0x607d8b
#define STYLE_GREY_SECONDARY_LIGHT 0x8eacbb
#define STYLE_GREY_SECONDARY_DARK 0x34515e
